management:
  security:
    enabled: false

spring:
  boot:
    admin:
      url: 'http://localhost:8888'

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.99.100:32768/TestDb
#    hikari:
#      data-source-class-name: org.postgresql.ds.PGSimpleDataSource

logging:
  level:
    org.springframework.web: 'DEBUG'
  file: 'my.log'

server:
  port: 8090

services:
  quotes:
    connectionString: 'http://gturnquist-quoters.cfapps.io/api/random'

persons:
  fucker:
    taxid: '2323-AAA-33434'

---

spring:
  profiles: dev

persons:
  fucker:
    taxid: '2323-AAA-33434-DEVELOPMENT'